@startuml

class Aluno {
    - String nome
    - int matricula
    + String getNome()
    + int getMatricula()
}

class Disciplina {
    - String nome
    + String getNome()
}

class Professor {
    - String nome
    - String departamento
    + String getNome()
    + String getDepartamento()
}

class Turma {
    - Disciplina disciplina
    - Professor professor
    - List<Aluno> alunosMatriculados
    - int MinAluno = 3
    - int MaxAluno = 60
    + Disciplina getDisciplina()
    + Professor getProfessor()
    + List<Aluno> getAlunosMatriculados()
    + boolean matricularAluno(Aluno aluno)
    + boolean verificarMinAluno()
    + boolean verificarMaxAluno()
}

class Matricula {
    - Aluno aluno
    - Turma turma
    - Date dataMatricula
    + Aluno getAluno()
    + Turma getTurma()
    + Date getDataMatricula()
    + String toString()
}

class SistemaCobranca {
    + void gerarCobranca(Aluno aluno, Turma turma)
}

Aluno "1" --> "0..*" Matricula
Turma "1" --> "0..*" Matricula
Professor "1" --> "0..*" Turma
Disciplina "1" --> "0..*" Turma
Turma "1" --> "0..*" Aluno : "alunosMatriculados"
Turma "1" --> "1" Professor
SistemaCobranca --> Matricula

@enduml
